import type { Case } from './types'

export const SAMPLE_SOURCE_DATABASE = 'SAMPLE — DEMONSTRATION DATA ONLY'

export const sampleCases: Case[] = [
  {
    id: 'sample-record-a',
    name: 'Sample Record A',
    photo_url: null,
    tribal_affiliation: 'Sample Nation',
    date_missing: '2024-01-15',
    date_found: null,
    status: 'missing',
    age_at_disappearance: null,
    location_name: 'Generic Northern Plains Location',
    latitude: 46.8083,
    longitude: -100.7837,
    country: 'US',
    state_province: 'ND',
    summary:
      'Clearly fictional demonstration record used only to show how a map popup could present case information.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'demonstration-case-02',
    name: 'Demonstration Case 02',
    photo_url: null,
    tribal_affiliation: 'Demonstration Community',
    date_missing: '2023-09-03',
    date_found: null,
    status: 'found',
    age_at_disappearance: null,
    location_name: 'Generic Pacific Northwest Location',
    latitude: 47.6062,
    longitude: -122.3321,
    country: 'US',
    state_province: 'WA',
    summary:
      'Placeholder sample data for interface testing; this record does not describe a real person or event.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sample-record-c',
    name: 'Sample Record C',
    photo_url: null,
    tribal_affiliation: 'Sample Nation',
    date_missing: '2022-06-21',
    date_found: null,
    status: 'murdered',
    age_at_disappearance: null,
    location_name: 'Generic Southwest Location',
    latitude: 35.0844,
    longitude: -106.6504,
    country: 'US',
    state_province: 'NM',
    summary:
      'Fictional sample record included to demonstrate status colors, clustering by region, and popup content.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'demonstration-case-04',
    name: 'Demonstration Case 04',
    photo_url: null,
    tribal_affiliation: 'Demonstration Community',
    date_missing: '2021-11-12',
    date_found: null,
    status: 'resolved',
    age_at_disappearance: null,
    location_name: 'Generic Upper Midwest Location',
    latitude: 44.9778,
    longitude: -93.265,
    country: 'US',
    state_province: 'MN',
    summary:
      'Synthetic record for the demo build; no real identity, location detail, or investigative detail is represented.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sample-record-e',
    name: 'Sample Record E',
    photo_url: null,
    tribal_affiliation: 'Sample Nation',
    date_missing: '2020-04-07',
    date_found: null,
    status: 'missing',
    age_at_disappearance: null,
    location_name: 'Generic Oklahoma Location',
    latitude: 35.4676,
    longitude: -97.5164,
    country: 'US',
    state_province: 'OK',
    summary:
      'Clearly labeled placeholder used to validate map rendering and status filtering concepts.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'demonstration-case-06',
    name: 'Demonstration Case 06',
    photo_url: null,
    tribal_affiliation: 'Demonstration Community',
    date_missing: '2024-03-18',
    date_found: null,
    status: 'missing',
    age_at_disappearance: null,
    location_name: 'Generic British Columbia Location',
    latitude: 49.2827,
    longitude: -123.1207,
    country: 'CA',
    state_province: 'BC',
    summary:
      'Fictional Canadian sample point for demonstration only; it is not sourced from a real case database.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sample-record-g',
    name: 'Sample Record G',
    photo_url: null,
    tribal_affiliation: 'Sample Nation',
    date_missing: '2022-12-02',
    date_found: null,
    status: 'found',
    age_at_disappearance: null,
    location_name: 'Generic Alberta Location',
    latitude: 53.5461,
    longitude: -113.4938,
    country: 'CA',
    state_province: 'AB',
    summary:
      'Placeholder record used to confirm that found-status markers and popup labels render correctly.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'demonstration-case-08',
    name: 'Demonstration Case 08',
    photo_url: null,
    tribal_affiliation: 'Demonstration Community',
    date_missing: '2019-08-30',
    date_found: null,
    status: 'murdered',
    age_at_disappearance: null,
    location_name: 'Generic Manitoba Location',
    latitude: 49.8951,
    longitude: -97.1384,
    country: 'CA',
    state_province: 'MB',
    summary:
      'Synthetic demo record for a status-color example; all descriptive details are intentionally generic.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sample-record-i',
    name: 'Sample Record I',
    photo_url: null,
    tribal_affiliation: 'Sample Nation',
    date_missing: '2023-05-10',
    date_found: null,
    status: 'resolved',
    age_at_disappearance: null,
    location_name: 'Generic Ontario Location',
    latitude: 45.4215,
    longitude: -75.6972,
    country: 'CA',
    state_province: 'ON',
    summary:
      'Fictional record included only to show that resolved records can appear alongside active records.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'demonstration-case-10',
    name: 'Demonstration Case 10',
    photo_url: null,
    tribal_affiliation: 'Demonstration Community',
    date_missing: '2021-02-24',
    date_found: null,
    status: 'missing',
    age_at_disappearance: null,
    location_name: 'Generic Northern Territory Location',
    latitude: 62.454,
    longitude: -114.3718,
    country: 'CA',
    state_province: 'NT',
    summary:
      'Clearly fictional northern sample point for layout, zoom, and marker-density testing.',
    source_urls: [],
    source_database: SAMPLE_SOURCE_DATABASE,
    additional_info: {},
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
]
